image:
  file: .gitpod/.gitpod.Dockerfile
tasks:
  - command: |
      # authenticate with AWS via OIDC so we can get access to S3
      gp idp login aws --role-arn arn:aws:iam::950174689815:role/shared-state-access-role

      # mount our S3 bucket to a local folder
      .gitpod/mount_s3.sh shared-state-test /workspace/shared-folder-sample-lib/shared

      # use a symlink to relocate the Maven artifact into the shared folder
      .gitpod/link.sh secretsauce /workspace/m2-repository/com/mycompany /workspace/shared-folder-sample-lib/shared
